package com.dhanuk.quickscanpro.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.layout.imePadding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Key
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Shuffle
import androidx.compose.material3.CenterAlignedTopAppBar
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.dhanuk.quickscanpro.ui.design.QsButton
import com.dhanuk.quickscanpro.ui.design.QsCard
import com.dhanuk.quickscanpro.ui.design.QsOutlinedButton
import com.dhanuk.quickscanpro.ui.design.SectionLabel
import com.dhanuk.quickscanpro.ui.theme.Caution
import com.dhanuk.quickscanpro.ui.theme.Danger
import com.dhanuk.quickscanpro.ui.theme.Positive
import com.dhanuk.quickscanpro.util.PasswordTools

@OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
@Composable
fun PasswordToolsScreen(onNavigateBack: () -> Unit) {
    val context = LocalContext.current
    var checkInput by rememberSaveable { mutableStateOf("") }
    var generated by rememberSaveable { mutableStateOf(PasswordTools.generate()) }

    val analysis = if (checkInput.isNotBlank()) PasswordTools.analyze(checkInput) else null

    Scaffold(
        contentWindowInsets = WindowInsets(0, 0, 0, 0),
        topBar = {
            CenterAlignedTopAppBar(
                windowInsets = WindowInsets(0, 0, 0, 0),
                title = { Text("Password Tools", style = MaterialTheme.typography.titleLarge) },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.centerAlignedTopAppBarColors(containerColor = MaterialTheme.colorScheme.background)
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .imePadding()
                .padding(horizontal = 20.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Spacer(Modifier.height(0.dp))

            Column {
                SectionLabel("Strength checker")
                QsCard {
                    OutlinedTextField(
                        value = checkInput,
                        onValueChange = { checkInput = it },
                        label = { Text("Type a password to test") },
                        singleLine = true,
                        shape = RoundedCornerShape(14.dp),
                        modifier = Modifier.fillMaxWidth()
                    )
                    val a = analysis
                    if (a != null) {
                        Spacer(Modifier.height(12.dp))
                        val color = when (a.strength) {
                            PasswordTools.Strength.VERY_WEAK, PasswordTools.Strength.WEAK -> Danger
                            PasswordTools.Strength.FAIR -> Caution
                            else -> Positive
                        }
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(
                                a.strength.label,
                                style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                                color = color,
                                modifier = Modifier.weight(1f)
                            )
                            Text("~${a.entropyBits} bits", style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
                        }
                        Spacer(Modifier.height(8.dp))
                        LinearProgressIndicator(
                            progress = { a.strength.score / 100f },
                            modifier = Modifier.fillMaxWidth().height(8.dp).clip(RoundedCornerShape(4.dp)),
                            color = color,
                            trackColor = MaterialTheme.colorScheme.surfaceContainerHigh
                        )
                        if (a.signals.isNotEmpty()) {
                            Spacer(Modifier.height(10.dp))
                            a.signals.forEach { signal ->
                                Text("• $signal", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }
                    }
                }
            }

            Column {
                SectionLabel("Secure generator")
                QsCard {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(
                            Icons.Filled.Key,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.padding(end = 8.dp)
                        )
                        Text(
                            generated,
                            style = MaterialTheme.typography.titleSmall.copy(fontFamily = FontFamily.Monospace),
                            color = MaterialTheme.colorScheme.onSurface,
                            modifier = Modifier.weight(1f)
                        )
                    }
                    Spacer(Modifier.height(10.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        QsOutlinedButton(
                            text = "Copy",
                            icon = Icons.Filled.ContentCopy,
                            modifier = Modifier.weight(1f),
                            onClick = { copy(context, generated) }
                        )
                        QsOutlinedButton(
                            text = "Regenerate",
                            icon = Icons.Filled.Refresh,
                            modifier = Modifier.weight(1f),
                            onClick = { generated = PasswordTools.generate() }
                        )
                    }
                }
            }

            QsButton(
                text = "Generate strong password",
                icon = Icons.Filled.Shuffle,
                onClick = { generated = PasswordTools.generate(18) }
            )

            Spacer(Modifier.height(8.dp))
        }
    }
}

private fun copy(context: Context, text: String) {
    (context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager)
        .setPrimaryClip(ClipData.newPlainText("password", text))
    Toast.makeText(context, "Copied", Toast.LENGTH_SHORT).show()
}
