package com.quickscanpro.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF00668B)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFC3E7FF)
val OnPrimaryContainer = Color(0xFF001E2D)
val Secondary = Color(0xFF4E616D)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFD1E5F4)
val OnSecondaryContainer = Color(0xFF091E28)
val Tertiary = Color(0xFF615A7D)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFE7DEFF)
val OnTertiaryContainer = Color(0xFF1D1736)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFF7F9FF)
val OnBackground = Color(0xFF181C1F)
val Surface = Color(0xFFF7F9FF)
val OnSurface = Color(0xFF181C1F)
val SurfaceVariant = Color(0xFFDDE3EA)
val OnSurfaceVariant = Color(0xFF41484D)
val Outline = Color(0xFF71787E)
val InverseSurface = Color(0xFF2D3134)
val InverseOnSurface = Color(0xFFEEF1F5)
val InversePrimary = Color(0xFF79D0FF)
